/**
 * export-manager.js — Sentinel Core Export Manager
 *
 * Builds and downloads Excel workbooks for individual sessions,
 * or bundles all sessions into a ZIP with carrier folder structure.
 *
 * Dependencies: XLSX (SheetJS), JSZip, CellLacParser
 *
 * Public API:
 *   ExportManager.buildOutputPath(session)                → {carrier, phone, filename, fullPath}
 *   ExportManager.buildWorkbook(session)                  → XLSX Workbook
 *   ExportManager.exportSingle(session)                   → void (browser download)
 *   ExportManager.exportZipBundle(sessions, summaryWb)    → Promise<Blob>
 *   ExportManager.buildSummaryWorkbook(sessions)          → XLSX Workbook
 */

const ExportManager = (() => {
  'use strict';

  // ── Author Signature ───────────────────────────────────────

  const SIGNATURE = {
    PRODUCT:      'TelecomPlatform',
    ORGANIZATION: 'Gravity Intelligence Lab',
    AUTHOR:       'Cao_Son_Hinh su_CNC',
    COPYRIGHT:    'Copyright © 2026',
    VERSION:      '4.2.1-SECURE',
  };

  function _appendSignatureSheet(wb) {
    const ts = new Date().toLocaleString('vi-VN', {
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
    });

    const rows = [
      [''],
      ['──────────────────────────────────────────────────────'],
      [''],
      ['Generated by', SIGNATURE.PRODUCT],
      [''],
      ['Organization', SIGNATURE.ORGANIZATION],
      [''],
      ['Designed & Architected by', SIGNATURE.AUTHOR],
      [''],
      ['Version', SIGNATURE.VERSION],
      ['Export Timestamp', ts],
      [''],
      [SIGNATURE.COPYRIGHT],
      [''],
      ['──────────────────────────────────────────────────────'],
    ];

    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 28 }, { wch: 42 }];

    // Style column A as label (muted)
    XLSX.utils.book_append_sheet(wb, ws, 'Signature');
  }

  // ── Helpers ────────────────────────────────────────────────

  function _sanitize(str) {
    return String(str || '')
      .replace(/[/\\:*?"<>|]/g, '_')
      .replace(/\s+/g, ' ')
      .trim() || 'unknown';
  }

  function _timestamp() {
    const d = new Date();
    return [
      d.getFullYear(),
      String(d.getMonth() + 1).padStart(2, '0'),
      String(d.getDate()).padStart(2, '0'),
      '_',
      String(d.getHours()).padStart(2, '0'),
      String(d.getMinutes()).padStart(2, '0'),
      String(d.getSeconds()).padStart(2, '0'),
    ].join('');
  }

  // ── buildOutputPath ────────────────────────────────────────

  function buildOutputPath(session) {
    const carrier  = _sanitize(session.carrierName || session.carrier || 'Unknown');
    const phone    = _sanitize(
      session.subscriber?.phone ||
      session.subscriber?.phone_raw ||
      session.fileName?.replace(/\.xlsx?$/i, '') ||
      'unknown'
    );
    const filename = phone + '_export_all.xlsx';
    return {
      carrier,
      phone,
      filename,
      fullPath: carrier + '/' + filename,
    };
  }

  // ── buildWorkbook ──────────────────────────────────────────

  function buildWorkbook(session) {
    if (!session.parseResult) {
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([['Không có dữ liệu']]), 'Empty');
      _appendSignatureSheet(wb);
      return wb;
    }

    // Re-attach derived data so CellLacParser.exportToExcel gets full picture
    const enrichedResult = Object.assign({}, session.parseResult, {
      pii:          session.subscriber || session.parseResult.pii || {},
      records:      session.records    || session.parseResult.records || [],
      _contacts:    session.contactsData  || {},
      _imei:        session.imeiData      || {},
      _location:    session.locationData  || {},
      carrier_name: session.carrierName   || session.parseResult.carrier_name,
      carrier:      session.carrier       || session.parseResult.carrier,
    });

    const wb = CellLacParser.exportToExcel(enrichedResult);
    _appendSignatureSheet(wb);
    return wb;
  }

  // ── exportSingle ───────────────────────────────────────────

  function exportSingle(session) {
    try {
      const wb   = buildWorkbook(session);
      const path = buildOutputPath(session);
      XLSX.writeFile(wb, path.filename);
    } catch (err) {
      console.error('[ExportManager] exportSingle failed:', err);
      alert('Xuất file thất bại: ' + err.message);
    }
  }

  // ── buildSummaryWorkbook ───────────────────────────────────

  function buildSummaryWorkbook(sessions) {
    const rows = (sessions || [])
      .filter(s => s.status === 'done')
      .map(s => {
        const timestamps = (s.records || [])
          .filter(r => r.timestamp)
          .map(r => String(r.timestamp))
          .sort();
        return {
          'Carrier':      s.carrierName || s.carrier || '—',
          'Format':       s.format      || '—',
          'File':         s.fileName    || '—',
          'Phone':        s.subscriber?.phone || '—',
          'Subscriber':   s.subscriber?.name  || '—',
          'Records':      (s.records || []).length,
          'Contacts':     Object.keys(s.contactsData || {}).length,
          'IMEI':         Object.keys(s.imeiData     || {}).length,
          'Locations':    Object.keys(s.locationData  || {}).length,
          'Start Date':   timestamps[0]?.slice(0, 10)              || '—',
          'End Date':     timestamps[timestamps.length - 1]?.slice(0, 10) || '—',
          'Confidence':   s.confidence != null ? (s.confidence * 100).toFixed(0) + '%' : '—',
          'Export Time':  new Date().toLocaleString('vi-VN'),
        };
      });

    const wb = XLSX.utils.book_new();
    const ws = rows.length > 0
      ? XLSX.utils.json_to_sheet(rows)
      : XLSX.utils.aoa_to_sheet([['Không có phiên nào hoàn thành']]);

    // Auto column widths
    if (rows.length > 0) {
      const keys = Object.keys(rows[0]);
      ws['!cols'] = keys.map(k => ({
        wch: Math.max(k.length, ...rows.map(r => String(r[k] || '').length)) + 2,
      }));
    }

    XLSX.utils.book_append_sheet(wb, ws, 'Summary');
    _appendSignatureSheet(wb);
    return wb;
  }

  // ── exportZipBundle ────────────────────────────────────────

  async function exportZipBundle(sessions, summaryWorkbook) {
    if (typeof JSZip === 'undefined') {
      throw new Error('JSZip chưa được tải. Không thể tạo ZIP.');
    }

    const zip  = new JSZip();
    const ts   = _timestamp();
    const root = 'Export_' + ts;

    // Summary.xlsx
    if (summaryWorkbook) {
      const summaryBytes = XLSX.write(summaryWorkbook, { bookType: 'xlsx', type: 'array' });
      zip.file(root + '/Summary.xlsx', summaryBytes);
    }

    // Per-session workbooks
    for (const session of sessions) {
      if (session.status !== 'done') continue;
      try {
        const wb    = buildWorkbook(session);
        const path  = buildOutputPath(session);
        const bytes = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
        zip.file(root + '/' + path.fullPath, bytes);
      } catch (err) {
        console.warn('[ExportManager] Skipping session', session.fileName, err.message);
      }
    }

    return zip.generateAsync({
      type:        'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });
  }

  // ── Public API ─────────────────────────────────────────────
  return {
    buildOutputPath,
    buildWorkbook,
    exportSingle,
    exportZipBundle,
    buildSummaryWorkbook,
  };
})();
